apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: php-pvc
  labels:
    name: php-pvc

spec:
  accessModes:
   - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---

apiVersion: v1
kind: Service
metadata:
  name: php
  labels:
    app: php
spec:
  ports:
    - port: 80
  selector:
    app: php
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: php
spec:
  selector:
    matchLabels:
      app: php
  replicas: 1
  template:
    metadata:
      labels:
        app: php
    spec:
      containers:
      - name: php-dep
        image: rootritesh/webserver-php
        ports:
        - containerPort: 80
        volumeMounts:
          - name: php-pvc
            mountPath: /var/www/html
      volumes:
      - name: php-pvc
        persistentVolumeClaim:
          claimName: php-pvc

